### PR TITLE
Bump dependencies

### PR DESCRIPTION
**Pull request by GaryJones**
Switch to caret, as that better understands semver.

### CODE REVIEW

**Comment by robneu** [comment]
I've been [using the .x versioning](https://github.com/wpsitecare/sitecare-plugin-config/blob/master/package.json#L18-L40) lately just to avoid having to bump these so frequently. It's probably a little more likely to create version compat problems, but eh...

**Comment by GaryJones** [comment]
The use of `^` should avoid the need for bumps, unless you want to have a specific minimum at a patch level.

**Comment by robneu** [comment]
Does that translate to anything newer than the specified version?

**Comment by GaryJones** [comment]
No - it's anything newer that bumps the patch or minor release, but not the major release.

So `^1.2.1` will allow 1.2.2, 1.3.0, 1.3.1 all the way upto < 2.0.0. Basically, everything that should still be backwards-compatible.

For releases that are not yet at version 1, then it treats the second digit change as potentially backwards incompatible, since the package is still considered to be in development.

So `^0.17.2` allows 0.17.3, and up to < 0.18.

`^` is preferred / the default instead of `~` for both NPM and Composer.

**Comment by robneu** [comment]
Doesn't that mean that `^1.2.1` is essentially the same as `1.x`?

**Comment by GaryJones** [comment]
At one level, yes, but when this package is used by someone, so this package's dependency becomes their dependency's dependency, the algorithm for getting a satisfactory set of dependencies can be made easier with the `^`, AIUI. @rdohms did explain it at PHP South West in terms of Composer, so I'm going on the assumption that it's the same for NPM too.

**Comment by robneu** [comment]
Interesting. I'll have to read up on it some more. It seems like `^1.2.1` would be the better format since it specifies a minimum version. `1.x` would basically mean (I think) that it's compat with everything back to `1.0`, so anything within that range would satisfy the dependency. 

I guess assuming the maintainer actually follows semver correctly (lol), that would be fine and make for the least about of duplicated packages due to version conflicts... but it would also allow older versions to be used which probably isn't great.

Bah. Versions. :beer:

**Comment by rdohms** [comment]
`1.x` or `1.*` will also install `1.2.0` where `^1.2.1`, makes it so nothing below 1.2.1 is used. Basically means composer has to look at less release when doing the matching dance.

npm does have some unique interpretations, so you may get some weird behaviour, I would suggest playing around with http://semver.npmjs.com/ to be sure.

**Comment by robneu** [comment]
Ah, that makes sense. Thanks for the link @rdohms, that's a pretty cool visualization of how the matching system works!

**Pull request merged**
